### ISSUE TITLE
New LIFX downlight?

### ISSUE THREAD

**Issue by Djelibeybi** [LIFX/products#22]
Can we please get `products.json` updated for product ID 121, i.e. the new Downlight?

**Comment by ristomatti** [comment]
I wonder if this is maintained anymore? If you know the ID and it's features, perhaps fork the repo and add it?

As I know you're a well known contributor to HA LIFX addon, I'd feel at easy to include it also to [node-lifx/lifx-lan-client](https://github.com/node-lifx/lifx-lan-client/) (and [node-red-contrib-node-lifx](https://github.com/ristomatti/node-red-contrib-node-lifx) which uses it), both of which I'm maintaining.

Since many Home Assistant users use Node-RED for it's automation, this could benefit people either transitioning to Home Assistant or preferring to still keep some parts of their automation independent of HA (e.g. myself).

**Comment by eminence** [comment]
> If you know the ID and it's features, perhaps fork the repo and add it?

Please also add a comment here, so others can integrate that data into their own libraries :)

**Comment by Djelibeybi** [comment]
I know that I have product ID 121 (which is the AU version). I can guess at its capabilities, but I don't know what the product IDs of the US/International versions are.

**Comment by thommo999** [comment]
The new products have been added in #23

**Comment by georgefst** [comment]
> I wonder if this is maintained anymore?

Fortunately (since I rely on this for generating code for my Haskell library), I've seen no real sign that it isn't. The only slight concern is that updating it doesn't seem to be part of the LIFX team's process when a new product is released. But they've always been responsive when prompted.
